# roles/Index_Management/tasks/rebuild_index.yml
---
- name: Reindex the specified index concurrently
  community.postgresql.postgresql_query:
    db: "{{ postgres_db }}"
    login_host: "{{ postgres_host }}"
    login_port: "{{ postgres_port }}"
    login_user: "{{ postgres_user }}"
    login_password: "{{ postgres_password }}"
    query: "REINDEX INDEX CONCURRENTLY {{ index_name }};"
  register: reindex_result

- name: Display reindex result
  debug:
    msg: "Reindex Concurrectly result: {{ reindex_result }}"
