---
- name: Reindex the specified index
  community.postgresql.postgresql_query:
    db: "{{ postgres_db }}"
    login_host: "{{ postgres_host }}"
    login_port: "{{ postgres_port }}"
    login_user: "{{ postgres_user }}"
    login_password: "{{ postgres_password }}"
    query: "REINDEX INDEX {{ index_name }};"  # Include schema name here
  register: reindex_result

- name: Display reindex result
  debug:
    msg: "Reindex result: {{ reindex_result }}"
