- name: Drop {{ idxname }} cascade
  community.postgresql.postgresql_idx:
    db: "{{ postgres_db }}"
    schema: "{{ schema_name }}"  # Add the schema parameter here
    idxname: "{{ idxname }}"
    state: absent
    cascade: "{{ cascade }}"
    concurrent: "{{ concurrent }}"
    login_host: "{{ postgres_host }}"
    login_port: "{{ postgres_port }}"
    login_user: "{{ postgres_user }}"
    login_password: "{{ postgres_password }}"
  tags: drop_index
